[package]
name = "example_egui"
version = "0.1.0"
edition = "2021"

[workspace]

[dependencies]
eframe = "0.32"
egui = "0.32"
dataset-ui-adapters = { path = "../vantage-ui-adapters", features = ["egui"] }
tokio = { version = "1.47", features = ["macros", "rt-multi-thread"] }
