tables:
  bakery:
    table: bakery
    columns:
      - name: id
        type: string
        flags: [id]
      - name: name
        type: string
        flags: [title, searchable, mandatory]
      - name: profit_margin
        type: int
        flags: [mandatory]
        rules:
          min: 0
          max: 100
    relations:
      - type: has_many
        name: clients
        foreign_key: bakery
        target: client
      - type: has_many
        name: products
        foreign_key: bakery
        target: product

  client:
    table: client
    columns:
      - name: id
        type: string
        flags: [id]
      - name: email
        type: string
        flags: [searchable]
        rules:
          email: true
      - name: name
        type: string
        flags: [title, searchable, mandatory]
      - name: contact_details
        type: string
        flags: [searchable]
      - name: is_paying_client
        type: bool
        default: false
      - name: bakery
        type: string
        flags: [mandatory]
      - name: metadata
    relations:
      - type: belongs_to
        name: bakery
        foreign_key: bakery
        target: bakery

  product:
    table: product
    columns:
      - name: id
        type: string
        flags: [id]
      - name: name
        type: string
        flags: [title, searchable, mandatory]
      - name: calories
        type: int
        flags: [mandatory]
        rules:
          min: 0
      - name: price
        type: int
        flags: [mandatory]
        rules:
          min: 1
      - name: bakery
        type: string
        flags: [mandatory]
      - name: is_deleted
        type: bool
        default: false
        flags: [hidden]
      - name: inventory
    relations:
      - type: belongs_to
        name: bakery
        foreign_key: bakery
        target: bakery

  order:
    table: order
    columns:
      - name: id
        type: string
        flags: [id]
      - name: bakery
        type: string
        flags: [mandatory]
      - name: is_deleted
        type: bool
        default: false
        flags: [hidden]
      - name: created_at
        type: datetime
        default: now
        flags: [mandatory]
      - name: lines
        type: array
        default: []
    relations:
      - type: belongs_to
        name: bakery
        foreign_key: bakery
        target: bakery
      - type: belongs_to
        name: client
        foreign_key: client
        target: client
