[workspace]
members = [
    "vantage",
    "vantage-expressions",
    "vantage-sql",
    "vantage-surrealdb",
    "vantage-mongodb",
    "bakery_model",
    "bakery_api",
    "surreal-client",
]
resolver = "2"
