[workspace]
members = [
    "vantage",
    "vantage-expressions",
    "vantage-sql",
    "vantage-surrealdb",
    "vantage-mongodb",
    "bakery_model",
    "bakery_model3",
    "bakery_api",
    "surreal-client",
    # "vantage-admin",
    "vantage-ui-adapters", "vantage-dataset", "vantage-table",
]
resolver = "2"
