import { StandardTableView } from "std-widgets.slint";

export component MainWindow inherits Window {
    title: "Bakery Model 3 - Slint Client List";
    width: 800px;
    height: 600px;

    in property <[[StandardListViewItem]]> table-rows;

    StandardTableView {
        width: parent.width - 40px;
        height: parent.height - 40px;
        x: 20px;
        y: 20px;

        columns: [
            { title: "Name" },
            { title: "Email" },
            { title: "Contact Details" },
            { title: "Paying Client" },
            { title: "Bakery" },
            { title: "Metadata" }
        ];

        rows: root.table-rows;
    }
}
