[package]
name = "vantage-core"
version = "0.3.0"
edition = "2024"

[lib]
doctest = false

[dependencies]
serde = { version = "1.0", features = ["derive"] }
thiserror = "1.0"
indexmap = "2.12"
owo-colors = { version = "4.2", optional = true }
atty = { version = "0.2", optional = true }
anyhow = { version = "1.0", optional = true }

[features]
default = ["colored-errors"]
colored-errors = ["owo-colors", "atty"]
anyhow-compat = ["anyhow"]

[dev-dependencies]
owo-colors = "4.2"
atty = "0.2"
