[package]
edition = "2024"
name = "vantage-expressions"
version = "0.3.0"
license = "MIT OR Apache-2.0"
authors = ["Romans Malinovskis <me@nearly.guru>"]
description = "Database agnostic expressions"
documentation = "https://docs.rs/vantage"
homepage = "https://romaninsh.github.io/vantage"
repository = "https://github.com/romaninsh/vantage"
readme = "../README.md"

[lib]
doctest = false

[dependencies]
async-trait = "0.1"
serde_json = "1.0.143"
thiserror = "2.0.16"

[dev-dependencies]
tokio = { version = "1.47", features = ["full"] }
tokio-test = "0.4"
chrono = { version = "0.4", features = ["serde"] }
