[package]
name = "dataset-ui-adapters"
version = "0.1.0"
edition = "2021"

[dependencies]
# Core dependencies always included
tokio = { version = "1.47", features = ["macros", "rt-multi-thread"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = "2.0"
async-trait = "0.1"
vantage-table = { path = "../vantage-table" }
vantage-expressions = { path = "../vantage-expressions" }
# vantage-surrealdb = { path = "../vantage-surrealdb" }

# Framework-specific dependencies (all optional)
egui = { version = "0.32", optional = true }
egui-data-table = { version = "0.8", optional = true }
egui_extras = { version = "0.32", optional = true }
gpui = { git = "https://github.com/zed-industries/zed.git", optional = true }
gpui-component = { git = "https://github.com/longbridge/gpui-component.git", optional = true }

slint = { version = "1.13", optional = true }
tauri = { version = "2.8", optional = true }
ratatui = { version = "0.29", optional = true }
crossterm = { version = "0.29", optional = true }
cursive = { version = "0.21", optional = true }
cursive_table_view = { version = "0.15", optional = true }

[dev-dependencies]
tokio-test = "0.4"

[features]
default = []
egui = ["dep:egui", "dep:egui-data-table", "dep:egui_extras"]
gpui = ["dep:gpui", "dep:gpui-component"]

slint = ["dep:slint"]
tauri = ["dep:tauri"]
ratatui = ["dep:ratatui", "dep:crossterm"]
cursive = ["dep:cursive", "dep:cursive_table_view"]
