//! SpacetimeDB persistence backend for Vantage — **incubating**.
//!
//! [SpacetimeDB](https://spacetimedb.com) is a relational database that is also
//! the application server: a WASM module holding the schema and the reducers
//! runs *inside* the database, and clients subscribe to SQL queries and are
//! pushed every subsequent change. That makes it the one backend where push is
//! the product rather than an add-on, which is why this driver exists — it is
//! the strongest available exercise of Vantage's change-subscription contract
//! (row-level deltas *and* server-side filtering).
//!
//! # Why this driver does not use `spacetimedb-sdk`
//!
//! The official Rust SDK is excellent, and it is the right choice for an
//! application that talks to one known module. It is the wrong choice here.
//! Its own documentation opens by stating that it *"depends on a set of
//! module-specific definitions autogenerated by the SpacetimeDB CLI"*, and the
//! types a dynamic client would need to implement (`SpacetimeModule`,
//! `DbConnection`, `DbUpdate`, `TableUpdate`) live in a `#[doc(hidden)]`
//! `__codegen` module carrying an explicit "may change incompatibly without a
//! major version bump" warning.
//!
//! The blocker is structural rather than cosmetic: codegen happens per module
//! at build time, whereas a Vantage datasource is named in YAML **at runtime**.
//! There is no point at which we know the schema early enough to generate
//! anything. So this crate owns its own connection and uses the official crates
//! for the wire format only — [`spacetimedb_lib`] for the module definition and
//! [`spacetimedb_sats`] for value decoding.
//!
//! # Capabilities, honestly
//!
//! SpacetimeDB's SQL has no `ORDER BY`, `OFFSET`, `GROUP BY`, `IN` or `LIKE`;
//! it does have `LIMIT` and `COUNT(*)`. Subscriptions are narrower still: whole
//! rows from a single table or view, `WHERE` only, at most a two-table indexed
//! `JOIN`. So this driver filters and counts server-side, and **refuses** to
//! sort, search or paginate rather than materialising the set and doing it
//! here. A `false` capability flag therefore means the operation genuinely does
//! not happen — not that it happens somewhere more expensive.

pub mod client;
pub mod schema;
pub(crate) mod sql;
pub mod value;
pub mod vista;

pub use client::SpacetimeDb;
pub use schema::{ModuleSchema, SchemaVersion};
pub use vista::{SpacetimeTableShell, SpacetimeVistaFactory};
