[package]
name = "example_iced"
version = "0.1.0"
edition = "2021"

[workspace]

[dependencies]
iced = "0.12"
dataset-ui-adapters = { path = "../vantage-ui-adapters", features = ["iced"] }
tokio = { version = "1.0", features = ["macros", "rt-multi-thread"] }
