name: SQLite Tests

on:
  pull_request:
    branches: ["main"]
    paths:
      - "vantage-sql/**"
      - ".github/workflows/sqlite.yaml"

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true
          key: "sqlite-workspace-v01"
          cache-workspace-crates: true
          cache-all-crates: true

      - name: Populate SQLite database
        run: |
          cd vantage-sql/scripts/sqlite
          bash ingress.sh

      - name: Build vantage-sql
        run: cargo build -p vantage-sql

      - name: Run vantage-sql tests
        run: cargo test -p vantage-sql

      - name: Run clippy
        run: cargo clippy -p vantage-sql --all-targets -- -D warnings
