name: UI Adapters Tests

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
    paths:
      - "vantage-ui-adapters/**"
      - ".github/workflows/ui-adapters.yaml"

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            pkg-config \
            libfontconfig1-dev \
            libfreetype6-dev \
            libx11-dev \
            libgl1-mesa-dev \
            libglib2.0-dev \
            libxkbcommon-dev \
            libxkbcommon-x11-dev \
            libgtk-3-dev \
            libatk1.0-dev \
            libcairo2-dev \
            libgdk-pixbuf2.0-dev \
            libpango1.0-dev \
            libsoup-3.0-dev \
            libwebkit2gtk-4.1-dev \
            build-essential \
            curl \
            wget \
            file \
            libxdo-dev \
            libssl-dev \
            libayatana-appindicator3-dev \
            librsvg2-dev

      - name: Build UI adapters
        run: cargo build -p dataset-ui-adapters --all-features

      - name: Run UI adapters tests
        run: cargo test -p dataset-ui-adapters --all-features

      - name: Check formatting
        run: cargo fmt -p dataset-ui-adapters -- --check
