name: UI Examples Build

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
    paths:
      - "example_*/**"
      - "vantage-ui-adapters/**"
      - ".github/workflows/ui-examples.yaml"

env:
  CARGO_TERM_COLOR: always

jobs:
  build-examples:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        example: [egui, iced, gpui, slint, tauri]

    steps:
      - uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true
          key: "ui-examples-${{ matrix.example }}"

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            pkg-config \
            libfontconfig1-dev \
            libfreetype6-dev \
            libx11-dev \
            libxcursor-dev \
            libxrandr-dev \
            libxi-dev \
            libxinerama-dev \
            libxxf86vm-dev \
            libgl1-mesa-dev \
            libasound2-dev \
            libpulse-dev \
            libgtk-3-dev \
            libwebkit2gtk-4.0-dev \
            libssl-dev

      - name: Install Tauri CLI (if needed)
        if: matrix.example == 'tauri'
        run: cargo install tauri-cli

      - name: Build example_${{ matrix.example }}
        working-directory: example_${{ matrix.example }}
        run: cargo build --release

      - name: Check example_${{ matrix.example }} formatting
        working-directory: example_${{ matrix.example }}
        run: cargo fmt -- --check

      - name: Run clippy on example_${{ matrix.example }}
        working-directory: example_${{ matrix.example }}
        run: cargo clippy --release -- -D warnings
