[package]
edition = "2024"
name = "vantage-redb"
version = "0.3.0"
license = "MIT OR Apache-2.0"
authors = ["Romans Malinovskis <me@nearly.guru>"]
description = "Vantage extension for redb"
documentation = "https://docs.rs/vantage"
homepage = "https://romaninsh.github.io/vantage"
repository = "https://github.com/romaninsh/vantage"
readme = "../README.md"


[dependencies]
async-trait = "0.1"
vantage-core = { path = "../vantage-core" }
vantage-expressions = { path = "../vantage-expressions" }
vantage-table = { path = "../vantage-table" }
vantage-dataset = { path = "../vantage-dataset" }
redb = "2.1"
indexmap = { version = "2.11.4", features = ["serde"] }
serde_json = { version = "1", features = [
    "preserve_order",
    "raw_value",
    "arbitrary_precision",
] }
serde = { version = "1.0", features = ["derive"] }
thiserror = "2.0"
tokio = { version = "1.47", features = ["full"] }
bincode = "1.3"
uuid = { version = "1.0", features = ["v4"] }
